### REGISTER
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name" : "najmul",
    "email": "najmul@gmail.com",
    "password": "najmul",
    "password_confirmation": "najmul"
}

### LOGIN
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "najmul@gmail.com",
    "password": "najmul"
}